---
    # Match_Mask_Measure
    pixel_scale: 2.5
    r_scale: 12
    field_pad: 50
    mag_limit: 15
    mag_saturate: 13
    draw: True
    save: True
    use_PS1_DR2: False
    
    # Run_PSF_Fitting
    n_spline: 3
    use_PS1_DR2: False
    pixel_scale: 2.5
    pad: 50
    mag_threshold: [13,10.5]
    mask_type: 'aper'
    mask_obj: ~
    SB_threshold: 24.5
    r_core: 24
    r_out: ~
    theta_cutoff: 1200
    n0: ~
    fit_n0: True
    fit_sigma: True
    fit_frac: False
    leg2d: False
    wid_strip: 24
    n_strip: 48
    n_cpu: 4
    parallel: False
    brightest_only: False
    draw_real: True
    nlive_init: ~
    sample_method: 'auto'
    draw: True
    print_progress: False
